spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: zhanmingzhe

  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名和下划线命名的自动转换